spring:
  application:
  name: WebSocket

  data:
    mongodb:
      uri: mongodb+srv://username:username@cluster0.pt3uyit.mongodb.net/chatDb?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8080
